<div class="upload_wrapper">
	<div id="dropbox-import" class="container upload_container lib-content ui-widget ui-widget-content block-shadow alpha-block padded" style="">
		
			<div class="tabbable">
				<div class="navbar navbar-inverse">
					<div class="navbar-inner">
					<div class="brand">
						<span>Dropbox : <?php echo $this->dbx_account['display_name']; ?></span>
					</div>
				<ul class="nav">
					  <li>
						<button class="btn btn-small" id="sclibrary-plus">
							<i class="icon-white icon-plus"></i><span id="sclib-plus-text"> Import Selected</span>
						</button>
						<button class="btn btn-small" id="sb-trash">
							<i class="icon-white icon-trash"></i>
						</button>
					  </li>
				</ul>
			</div>
		</div>

		<!-- processing message -->
		<div id="import_status" class="library_import" style="display:none"><div>File import in progress...</div><img src="/css/images/file_import_loader.gif"></img></div>	
		<div id="alert-box" class="alert" style="display:none;margin:10px 0;">
		  <span class="plupload_upload_status"></span>
		  <button type="button" class="close" data-dismiss="alert">&times;</button>
		</div>

		<div class="directory-browser block-shadow">
		<div class="current">
			<span class="<?php echo $this->items['icon']; ?>">
				<?php $breadcrumbs = explode('/', $this->items['path']); ?>
				<?php $crumb_path = ""; ?>
				<ul class="breadcrumb">
					<label>Current: </label>
					<li class="folder root-dir">
						<a href="/dropbox-import?path=/"><i class="icon-folder-open"></i>&nbsp;/</a>
					</li>
				<?php foreach($breadcrumbs as $breadcrumb): ?>
					<?php if(!empty($breadcrumb)): ?>
						<?php $crumb_path .= "/" . $breadcrumb; ?>
						<li class="folder leaf-dir">
							<a href="/dropbox-import?path=<?php echo $crumb_path; ?>">
							<i class="icon-folder-open"></i>&nbsp;
								<?php echo basename($breadcrumb); ?>
							</a>
						</li>
					<?php endif; ?>
				<?php endforeach; ?>
				</ul>
			</span>
		</div>
		<?php if(empty($this->items['contents'])): ?>
			<div id="alert-box" class="alert" style="margin:10px 0;">
			  <span class="plupload_upload_status">Empty directory.</span>
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			</div>
		<?php else: ?>
		<form class="dropbox-items">
			<ul class="tree">
				<?php foreach($this->items['contents'] as $index => $item): ?>
					<li class="leaf <?php echo $item['icon']; ?>">
						<span>
							<?php if($item['is_dir']): ?>
								<a href="/dropbox-import?path=<?php echo $item['path']; ?>">
									<i class="icon-folder-close"></i>&nbsp;<?php echo basename($item['path']); ?>
								</a>
							<?php elseif(!strncmp($item['mime_type'], 'audio', 5)): ?>
								<!-- audio item -->
								<input type="radio" name="dropbox_files"value="<?php echo $item['path']; ?>" />
								<i class="icon-headphones"></i>
								<?php echo basename($item['path']); ?>
							<?php endif; ?>
						</span>
					</li>
				<?php endforeach; ?>
			</ul>
		</form>
		<?php endif; ?>

	</div><!-- /.directory-browser -->

	<pre>
		<?php //print_r($this->items); ?>
	</pre>




	</div><!-- /#dropbox-import -->
</div> <!-- /.upload_wrapper -->

