<div class="upload_wrapper">
	<div id="usimdirect-import" class="container upload_container lib-content ui-widget ui-widget-content block-shadow alpha-block padded" style="">
		
			<div class="tabbable">
				<div class="navbar navbar-inverse">
					<div class="navbar-inner">
					<div class="brand">
						<span><a href="http://direct.voanews.com" target="_blank">USIM Direct</a></span>
					</div>
				<ul class="nav">
					  <li>
						<button class="btn btn-small" id="sclibrary-plus">
							<i class="icon-white icon-plus"></i><span id="sclib-plus-text"> Import Selected</span>
						</button>
						<button class="btn btn-small" id="sb-trash">
							<i class="icon-white icon-trash"></i>
						</button>
					  </li>
				</ul>
			</div>
		</div>

		<!-- processing message -->
		<div id="import_status" class="library_import" style="display:none"><div>File import in progress...</div><img src="/css/images/file_import_loader.gif"></img></div>	
		<div id="alert-box" class="alert" style="display:none;margin:10px 0;">
		  <span class="plupload_upload_status"></span>
		  <button type="button" class="close" data-dismiss="alert">&times;</button>
		</div>

				<div class="tab-content">

					<!-- usim direct track list -->
			        <div class="dataTables_wrapper">

				        <div class="dataTables_scrolling scprofile" style="max-height: 400px;">
						   <table id="sclibrary_display" cellpadding="0" cellspacing="0" class="datatable dataTable" aria-describedby="sclibrary_display_info">
								<thead>
						         <tr role="row">
						            <th class="sclibrary_checkbox ui-state-default" tabindex="0" rowspan="1" colspan="1" style="width: 25px;" aria-label="">
						               <div class="DataTables_sort_wrapper"><span class="DataTables_sort_icon"></span></div>
						            </th>
						            <th class="sclibrary_title ui-state-default" tabindex="0" rowspan="1" colspan="1" style="width: 170px;" aria-label="Title: activate to sort column ascending">
						               <div class="DataTables_sort_wrapper">Title<span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-n"></span></div>
						            </th>
						            <th class="sclibrary_creator ui-state-default" tabindex="0" rowspan="1" colspan="1" style="width: 160px;" aria-label="Username: activate to sort column ascending">
						               <div class="DataTables_sort_wrapper">Username<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
						            </th>
						            <th class="sclibrary_length ui-state-default" tabindex="0" rowspan="1" colspan="1" style="width: 80px;" aria-label="Length: activate to sort column ascending">
						               <div class="DataTables_sort_wrapper">Length<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
						            </th>
						            <th class="sclibrary_upload_time ui-state-default" tabindex="0" rowspan="1" colspan="1" style="width: 125px;" aria-label="Created: activate to sort column ascending">
						               <div class="DataTables_sort_wrapper">Created<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
						            </th>
						         </tr>
						      </thead>

						      <tbody role="alert" aria-live="polite" aria-relevant="all">
							  <?php foreach ($this->tracks as $index => $track): ?>
						         <tr class="<?php echo $index % 2 ? 'odd' : 'even'; ?> audio ui-draggable" id="item_<?php echo $track->nid; ?>">
						            <td class="usimdirect_library_checkbox"><input type="radio" name="usimdirect_files" value="<?php echo $track->nid; ?>" /></td>
						            <td class="library_title sorting_1"><?php echo $track->node->title; ?></td>
						            <td class="library_creator"><?php echo $track->node->field_credit->und[0]->value; ?></td>
						            <td class="library_length">
										<?php $total_seconds = $track->node->field_duration->und[0]->value; ?>
									    <?php echo gmdate("H:i:s", $total_seconds); ?>
						            </td>
						            <td class="library_upload_time"><?php echo date('c', $track->node->created); ?></td>
						         </tr>
							 <?php endforeach ?>

							</tbody>
						</table>

					</div><!-- ./scprofile -->
				</div><!-- /.dataTables_wrapper -->


			</div> <!-- /.tab-content -->

		</div><!-- /.tabbable -->



	</div><!-- /#usimdirect-import -->
</div> <!-- /.upload_wrapper -->

