<form method="<?php echo $this->element->getMethod() ?>" enctype="multipart/form-data">

    <?php echo $this->element->getSubform('preferences_general') ?>
    
    <h3 class="collapsible-header" id="email-server-heading"><span class="arrow-icon"></span><? echo _("Email / Mail Server Settings"); ?></h3>
    <div class="collapsible-content" id="email-server-settings">
        <?php echo $this->element->getSubform('preferences_email_server') ?>
    </div>

    <h3 class="collapsible-header" id="soundcloud-heading"><span class="arrow-icon"></span><? echo _("SoundCloud Settings") ?></h3>

    <div class="collapsible-content" id="soundcloud-settings">
        <?php echo $this->element->getSubform('preferences_soundcloud') ?>
    </div>

    <h3 class="collapsible-header" id="usimdirect-heading"><span class="arrow-icon"></span><? echo _("USIM Direct Settings") ?></h3>
    <div class="collapsible-content" id="usimdirect-settings">
        <?php echo $this->element->getSubform('preferences_usimdirect') ?>
    </div>

    <h3 class="collapsible-header" id="dropbox-heading"><span class="arrow-icon"></span><? echo _("Dropbox Settings") ?></h3>
    <div class="collapsible-content" id="dropbox-settings">
        <?php echo $this->element->getSubform('preferences_dropbox') ?>
    </div>

</form>
